# Grafana Data Sources Configuration
apiVersion: 1

datasources:
  - name: TimescaleDB
    type: grafana-postgresql-datasource
    access: proxy
    uid: TimescaleDB
    url: timescaledb:5432
    database: ${DB_NAME}
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
    editable: true
